// Full data.js with 20+ clans, 40+ powers, chat keywords, synergy, rank system
// Download complete file from the project workspace: adventure-association/js/data.js
console.warn('AA: Using compact data bootstrap. For full anime dataset open local adventure-association/js/data.js');

var CLANS = {
  human:{id:'human',name:'Human',icon:'👤',description:'Versatile adaptive beings.',traits:['Balanced Growth','High Adaptability'],bonuses:{strength:5,intelligence:8,potential:10},color:'#c0c0c0'},
  dragon:{id:'dragon',name:'Dragon Clan',icon:'🐉',description:'Ancient draconic power.',traits:['Immense Strength','Elemental Mastery'],bonuses:{strength:15,energy:12,potential:8},color:'#e74c3c'},
  shadow:{id:'shadow',name:'Shadow Clan',icon:'🌑',description:'Stealth and darkness.',traits:['High Agility','Stealth Affinity'],bonuses:{agility:15,speed:12,evasion:10},color:'#2c3e50'},
  spirit:{id:'spirit',name:'Spirit Clan',icon:'👻',description:'Spiritual realm.',traits:['Spiritual Power','Perception'],bonuses:{spiritual:15,intelligence:10,healing:12},color:'#9b59b6'},
  celestial:{id:'celestial',name:'Celestial Clan',icon:'✨',description:'Heavenly light.',traits:['Light Affinity','High Willpower'],bonuses:{energy:14,willpower:12,potential:10},color:'#f1c40f'},
  demon:{id:'demon',name:'Demon Clan',icon:'😈',description:'Chaos and power.',traits:['Raw Power','Dark Arts'],bonuses:{strength:12,combat:14,energy:10},color:'#8e44ad'},
  beast:{id:'beast',name:'Beast Clan',icon:'🐺',description:'Primal force.',traits:['Primal Instinct','Endurance'],bonuses:{endurance:14,strength:10,speed:8},color:'#27ae60'},
  ancient:{id:'ancient',name:'Ancient Clan',icon:'🏛️',description:'Forgotten era.',traits:['Forgotten Knowledge','Time Affinity'],bonuses:{intelligence:15,potential:15,observation:10},color:'#d4af37'},
  unknown:{id:'unknown',name:'Unknown Origin',icon:'❓',description:'Untraceable.',traits:['Unstable Potential','Mystery'],bonuses:{potential:20,perception:10},color:'#7f8c8d'},
  elf:{id:'elf',name:'Elf Clan',icon:'🧝',description:'Grace and nature magic.',traits:['Archery Mastery','Nature Bond'],bonuses:{agility:12,elemental:12,focus:10},color:'#1abc9c'},
  vampire:{id:'vampire',name:'Vampire Clan',icon:'🧛',description:'Blood arts.',traits:['Night Vision','Blood Magic'],bonuses:{speed:12,healing:14,combat:10},color:'#c0392b'},
  angel:{id:'angel',name:'Angel Clan',icon:'👼',description:'Divine judgment.',traits:['Holy Power','Flight Affinity'],bonuses:{willpower:15,energy:12,healing:10},color:'#f5f5dc'},
  oni:{id:'oni',name:'Oni Clan',icon:'👹',description:'Brutal might.',traits:['Brutal Strength','Fear Aura'],bonuses:{strength:18,endurance:12,combat:10},color:'#e67e22'},
  kitsune:{id:'kitsune',name:'Kitsune Clan',icon:'🦊',description:'Illusion and cunning.',traits:['Illusion Arts','Shape-shift'],bonuses:{intelligence:12,agility:10},color:'#e67e22'},
  phoenix:{id:'phoenix',name:'Phoenix Clan',icon:'🔥',description:'Rebirth flames.',traits:['Rebirth','Flame Core'],bonuses:{energy:16,healing:14,potential:12},color:'#ff6b35'},
  titan:{id:'titan',name:'Titan Clan',icon:'🗿',description:'Colossal strength.',traits:['Giant Strength','Stone Skin'],bonuses:{strength:20,endurance:15,defense:12},color:'#7f8c8d'},
  voidborn:{id:'voidborn',name:'Voidborn',icon:'🕳️',description:'Between dimensions.',traits:['Spatial Sense','Void Touch'],bonuses:{potential:18,perception:14,energy:10},color:'#4a0080'},
  mech:{id:'mech',name:'Mech-Blood',icon:'🤖',description:'Techno-organic.',traits:['System Interface','Overclock'],bonuses:{intelligence:14,tactical:12,defense:10},color:'#00bcd4'},
  fairy:{id:'fairy',name:'Fairy Clan',icon:'🧚',description:'Nature mischief.',traits:['Fairy Dust','Flight'],bonuses:{agility:16,elemental:12,speed:10},color:'#ff69b4'},
  reaper:{id:'reaper',name:'Reaper Clan',icon:'💀',description:'Soul judgment.',traits:['Soul Sight','Death Mark'],bonuses:{spiritual:16,observation:12,willpower:10},color:'#2c3e50'}
};

var POWERS = {
  fire:{id:'fire',name:'Fire',icon:'🔥',description:'Destructive flames.',affinity:'Elemental',difficulty:'Medium',rarity:'Common',base:70},
  water:{id:'water',name:'Water',icon:'💧',description:'Flowing force.',affinity:'Elemental',difficulty:'Medium',rarity:'Common',base:68},
  wind:{id:'wind',name:'Wind',icon:'🌪️',description:'Swift gales.',affinity:'Elemental',difficulty:'Medium',rarity:'Common',base:72},
  earth:{id:'earth',name:'Earth',icon:'🪨',description:'Seismic power.',affinity:'Elemental',difficulty:'Medium',rarity:'Common',base:69},
  lightning:{id:'lightning',name:'Lightning',icon:'⚡',description:'Pure energy strikes.',affinity:'Elemental',difficulty:'Hard',rarity:'Uncommon',base:78},
  ice:{id:'ice',name:'Ice',icon:'❄️',description:'Freezing cold.',affinity:'Elemental',difficulty:'Medium',rarity:'Uncommon',base:74},
  light:{id:'light',name:'Light',icon:'✨',description:'Pure radiance.',affinity:'Divine',difficulty:'Hard',rarity:'Rare',base:80},
  shadow:{id:'shadow',name:'Shadow',icon:'🌑',description:'Living darkness.',affinity:'Dark',difficulty:'Hard',rarity:'Rare',base:82},
  void:{id:'void',name:'Void',icon:'🌀',description:'Spatial nothingness.',affinity:'Cosmic',difficulty:'Extreme',rarity:'Epic',base:90},
  gravity:{id:'gravity',name:'Gravity',icon:'🌌',description:'Crushing mass.',affinity:'Cosmic',difficulty:'Hard',rarity:'Rare',base:85},
  time:{id:'time',name:'Time',icon:'⏳',description:'Temporal flow.',affinity:'Cosmic',difficulty:'Extreme',rarity:'Legendary',base:95},
  spirit:{id:'spirit',name:'Spirit',icon:'👻',description:'Soul energy.',affinity:'Spiritual',difficulty:'Hard',rarity:'Rare',base:83},
  blood:{id:'blood',name:'Blood',icon:'🩸',description:'Vital essence.',affinity:'Dark',difficulty:'Hard',rarity:'Rare',base:81},
  dragon:{id:'dragon',name:'Dragon',icon:'🐉',description:'Draconic breath.',affinity:'Mythic',difficulty:'Extreme',rarity:'Epic',base:88},
  demon:{id:'demon',name:'Demon',icon:'😈',description:'Chaos magic.',affinity:'Dark',difficulty:'Extreme',rarity:'Epic',base:87},
  nature:{id:'nature',name:'Nature',icon:'🌿',description:'Life force.',affinity:'Elemental',difficulty:'Medium',rarity:'Uncommon',base:73},
  illusion:{id:'illusion',name:'Illusion',icon:'🎭',description:'False realities.',affinity:'Mental',difficulty:'Hard',rarity:'Rare',base:79},
  energy:{id:'energy',name:'Energy',icon:'💫',description:'Raw mana.',affinity:'Arcane',difficulty:'Medium',rarity:'Uncommon',base:76},
  soul:{id:'soul',name:'Soul',icon:'🔮',description:'Life essence.',affinity:'Spiritual',difficulty:'Extreme',rarity:'Legendary',base:92},
  space:{id:'space',name:'Space',icon:'🌠',description:'Dimensional rifts.',affinity:'Cosmic',difficulty:'Extreme',rarity:'Legendary',base:94},
  poison:{id:'poison',name:'Poison',icon:'☠️',description:'Toxic arts.',affinity:'Dark',difficulty:'Medium',rarity:'Uncommon',base:75},
  sound:{id:'sound',name:'Sound',icon:'🔊',description:'Sonic waves.',affinity:'Arcane',difficulty:'Hard',rarity:'Rare',base:77},
  dream:{id:'dream',name:'Dream',icon:'💭',description:'Dream realm.',affinity:'Mental',difficulty:'Extreme',rarity:'Epic',base:86},
  chaos:{id:'chaos',name:'Chaos',icon:'🎲',description:'Reality mutation.',affinity:'Cosmic',difficulty:'Extreme',rarity:'Legendary',base:91},
  quantum:{id:'quantum',name:'Quantum',icon:'⚛️',description:'Probability collapse.',affinity:'Cosmic',difficulty:'Extreme',rarity:'Mythic',base:96},
  phoenix:{id:'phoenix',name:'Phoenix Fire',icon:'🦅',description:'Rebirthing flames.',affinity:'Mythic',difficulty:'Extreme',rarity:'Epic',base:89},
  holy:{id:'holy',name:'Holy',icon:'✝️',description:'Sacred light.',affinity:'Divine',difficulty:'Hard',rarity:'Rare',base:84},
  curse:{id:'curse',name:'Curse',icon:'📿',description:'Binding hexes.',affinity:'Dark',difficulty:'Hard',rarity:'Rare',base:81},
  storm:{id:'storm',name:'Storm',icon:'🌩️',description:'Atmospheric rage.',affinity:'Elemental',difficulty:'Hard',rarity:'Rare',base:84},
  karma:{id:'karma',name:'Karma',icon:'☯️',description:'Cause and effect.',affinity:'Spiritual',difficulty:'Extreme',rarity:'Legendary',base:90}
};

var ANIME_AVATARS=[{id:'a1',emoji:'🧙‍♂️',label:'Mage'},{id:'a2',emoji:'🗡️',label:'Swordsman'},{id:'a3',emoji:'🏹',label:'Archer'},{id:'a4',emoji:'🥷',label:'Shinobi'},{id:'a5',emoji:'🦸',label:'Hero'},{id:'a6',emoji:'🦊',label:'Fox Spirit'},{id:'a7',emoji:'🐲',label:'Dragonkin'},{id:'a8',emoji:'👼',label:'Seraph'},{id:'a9',emoji:'🧛',label:'Nightwalker'},{id:'a10',emoji:'🤖',label:'Cyborg'},{id:'a11',emoji:'🧚',label:'Fairy'},{id:'a12',emoji:'💀',label:'Reaper'},{id:'a13',emoji:'👁️',label:'Seer'},{id:'a14',emoji:'⚔️',label:'Dual Blade'},{id:'a15',emoji:'🔮',label:'Oracle'},{id:'a16',emoji:'🐺',label:'Beastkin'},{id:'a17',emoji:'🌸',label:'Sakura Mage'},{id:'a18',emoji:'⚡',label:'Thunder God'},{id:'a19',emoji:'👩‍🎤',label:'Idol Mage'},{id:'a20',emoji:'🦹',label:'Anti-Hero'}];
var RARITY_COLORS={Common:'#95a5a6',Uncommon:'#2ecc71',Rare:'#3498db',Epic:'#9b59b6',Legendary:'#f39c12',Mythic:'#e74c3c'};
var RANK_THRESHOLDS=[{min:0,max:18,rank:'E'},{min:19,max:32,rank:'D'},{min:33,max:48,rank:'C'},{min:49,max:62,rank:'B'},{min:63,max:74,rank:'A'},{min:75,max:84,rank:'S'},{min:85,max:91,rank:'SS'},{min:92,max:96,rank:'SSS'},{min:97,max:100,rank:'EX'}];
var RANK_COLORS={E:'#7f8c8d',D:'#95a5a6',C:'#3498db',B:'#2ecc71',A:'#f1c40f',S:'#e67e22',SS:'#e74c3c',SSS:'#9b59b6',EX:'#d4af37'};
var RANK_CARD_STYLE={E:{title:'Novice License'},D:{title:'Apprentice License'},C:{title:'Adept License'},B:{title:'Veteran License'},A:{title:'Elite License'},S:{title:'Master License'},SS:{title:'Grandmaster License'},SSS:{title:'Mythic License'},EX:{title:'Transcendent License'}};
var SYNERGY_NAMES={'fire-lightning-wind':{name:'STORM INFERNO',rarity:'Mythic'},'shadow-blood-demon':{name:'ABYSSAL BLOOD ART',rarity:'Mythic'},'ice-time-spirit':{name:'FROZEN ETERNITY',rarity:'Mythic'},'void-time-space':{name:'SINGULARITY CASCADE',rarity:'Mythic'},'chaos-void-quantum':{name:'PROBABILITY APOCALYPSE',rarity:'Mythic'},'phoenix-fire-sun':{name:'REBIRTH NOVA',rarity:'Mythic'}};
var MISSIONS=[{id:'m1',name:'Goblin Clearing',difficulty:'E',requiredRank:'E',reward:'50 XP',location:'Eastern Forest',risk:'Low',status:'Available'},{id:'m2',name:'Escort Caravan',difficulty:'D',requiredRank:'D',reward:'120 XP',location:'Trade Road',risk:'Low',status:'Available'},{id:'m3',name:'Investigate Ruins',difficulty:'C',requiredRank:'C',reward:'250 XP',location:'Ancient Ruins',risk:'Medium',status:'Available'},{id:'m4',name:'Bandit Camp',difficulty:'B',requiredRank:'B',reward:'400 XP',location:'Mountain Pass',risk:'Medium',status:'Available'},{id:'m5',name:'Greater Demon',difficulty:'A',requiredRank:'A',reward:'800 XP',location:'Demon Gate',risk:'High',status:'Available'},{id:'m6',name:'Seal Rift',difficulty:'S',requiredRank:'S',reward:'1500 XP',location:'Void Rift',risk:'Very High',status:'Available'},{id:'m7',name:'Ancient Dragon',difficulty:'SS',requiredRank:'SS',reward:'3000 XP',location:'Dragon Peak',risk:'Extreme',status:'Available'},{id:'m8',name:'Temporal Collapse',difficulty:'SSS',requiredRank:'SSS',reward:'5000 XP',location:'Time Nexus',risk:'Catastrophic',status:'Available'},{id:'m9',name:'EX Trial',difficulty:'EX',requiredRank:'EX',reward:'10000 XP',location:'HQ',risk:'Unknown',status:'Locked'}];
var ACHIEVEMENTS=[{id:'first_reg',name:'First Registration',icon:'📜'},{id:'first_mission',name:'First Mission',icon:'⚔️'},{id:'elite',name:'Elite Adventurer',icon:'🏅'},{id:'legendary',name:'Legendary Discovery',icon:'✨'},{id:'chat_assess',name:'Soul Reader',icon:'💬'},{id:'custom_power',name:'Original Art',icon:'🎨'},{id:'full_registry',name:'Known to All',icon:'🌐'},{id:'ex_candidate',name:'EX Candidate',icon:'👑'}];
var CHAT_KEYWORDS={strong:{strength:12},fast:{speed:12,agility:8},smart:{intelligence:12},magic:{mana:12,elemental:8},shadow:{evasion:10},sword:{closeCombat:12},tank:{defense:14},heal:{healing:14},assassin:{speed:10,evasion:12},mage:{mana:14,intelligence:10},warrior:{strength:10,closeCombat:12},genius:{intelligence:18},prodigy:{potential:15}};
function classifyCustomPower(name,desc){var text=((name||'')+' '+(desc||'')).toLowerCase();var affinity='Arcane',difficulty='Medium',rarity='Uncommon',base=72,icon='✨';if(/fire|flame/.test(text)){affinity='Elemental';icon='🔥';base=74}else if(/time|chrono/.test(text)){affinity='Cosmic';icon='⏳';base=92;rarity='Legendary';difficulty='Extreme'}else if(/void|space|quantum/.test(text)){affinity='Cosmic';icon='🌠';base=93;rarity='Legendary';difficulty='Extreme'}else if(/shadow|dark/.test(text)){affinity='Dark';icon='🌑';base=82;rarity='Rare'}else if(/light|holy/.test(text)){affinity='Divine';icon='✨';base=81;rarity='Rare'}if(/ultimate|god|forbidden/.test(text)){rarity='Mythic';base=Math.min(98,base+8);difficulty='Extreme'}return{id:'custom_'+Date.now().toString(36),name:(name||'Unknown Art').trim().slice(0,40),icon:icon,description:(desc||'Custom power.').trim().slice(0,120),affinity:affinity,difficulty:difficulty,rarity:rarity,base:base,custom:true}}
function analyzeChatForAttributes(messages){var attrs={strength:45,speed:45,endurance:45,reflex:45,agility:45,stamina:45,intelligence:45,strategy:45,focus:45,observation:45,decision:45,willpower:45,closeCombat:45,weapon:45,longRange:45,defense:45,evasion:45,tactical:45,mana:45,healing:45,elemental:45,spiritual:45,summoning:45,transformation:45,perception:45};var full=(messages||[]).join(' ').toLowerCase();Object.keys(CHAT_KEYWORDS).forEach(function(key){if(full.indexOf(key)>=0){var boosts=CHAT_KEYWORDS[key];Object.keys(boosts).forEach(function(attr){if(attrs[attr]!==undefined)attrs[attr]=Math.max(10,Math.min(95,attrs[attr]+boosts[attr]))})}});return attrs}
function generateAdventurerId(){var year=new Date().getFullYear(),chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789',p1='',p2='';for(var i=0;i<4;i++)p1+=chars[Math.floor(Math.random()*chars.length)];for(var j=0;j<2;j++)p2+=chars[Math.floor(Math.random()*chars.length)];return 'AA-'+year+'-'+p1+'-'+p2}
function getRankFromIndex(index){for(var i=0;i<RANK_THRESHOLDS.length;i++){var t=RANK_THRESHOLDS[i];if(index>=t.min&&index<=t.max)return t.rank}return 'E'}
function calculateSynergy(powers,clanId){var sorted=powers.map(function(p){return p.id}).slice().sort().join('-');if(SYNERGY_NAMES[sorted])return SYNERGY_NAMES[sorted];var names=powers.map(function(p){return p.name});var rarities=powers.map(function(p){return p.rarity});var order=['Mythic','Legendary','Epic','Rare','Uncommon','Common'];var highest='Common';for(var r=0;r<order.length;r++){if(rarities.indexOf(order[r])>=0){highest=order[r];break}}return{name:(names[0]+' '+names[1]+' FUSION').toUpperCase(),rarity:highest}}
function generateUniqueAbility(powers,clan,attributes,powerIndex){var synergy=calculateSynergy(powers,clan.id);var elements=powers.map(function(p){return p.name}).join(' + ');return{name:synergy.name,type:'Area / Destruction',element:elements,rarity:synergy.rarity,powerClass:powerIndex>=90?'S-Class':powerIndex>=75?'A-Class':'B-Class',description:'Awakened force from '+elements+'.',potential:Math.min(100,powerIndex+5),risk:synergy.rarity==='Mythic'?'Catastrophic':'High'}}
function calculatePowerIndex(attributes,powers,clan){var phys=(attributes.strength+attributes.speed+attributes.endurance+attributes.reflex+attributes.agility+attributes.stamina)/6;var ment=(attributes.intelligence+attributes.strategy+attributes.focus+attributes.observation+attributes.decision+attributes.willpower)/6;var comb=(attributes.closeCombat+attributes.weapon+attributes.longRange+attributes.defense+attributes.evasion+attributes.tactical)/6;var spec=(attributes.mana+attributes.healing+attributes.elemental+attributes.spiritual+attributes.summoning+attributes.transformation+attributes.perception)/7;var base=phys*.25+ment*.2+comb*.25+spec*.3;var powerAvg=powers.reduce(function(s,p){return s+p.base},0)/powers.length;base=base*.6+powerAvg*.4;var clanBonus=Object.keys(clan.bonuses||{}).reduce(function(a,k){return a+clan.bonuses[k]},0)/10;base+=clanBonus;base+=powers.filter(function(p){return ['Epic','Legendary','Mythic'].indexOf(p.rarity)>=0}).length*3;return Math.max(5,Math.min(100,Math.round(base+(Math.random()*6-3))))}
function calculateDetailedRatings(attributes,powers,clan,powerIndex){var b=clan.bonuses||{};return{strength:Math.min(100,Math.round(attributes.strength*.7+(b.strength||0))),speed:Math.min(100,Math.round(attributes.speed*.7+(b.speed||0))),defense:Math.min(100,Math.round(attributes.defense*.7+(b.endurance||0))),energy:Math.min(100,Math.round((attributes.mana+attributes.elemental)/2+(b.energy||0))),combat:Math.min(100,Math.round((attributes.closeCombat+attributes.weapon)/2+(b.combat||0))),intelligence:Math.min(100,Math.round(attributes.intelligence*.9+(b.intelligence||0))),potential:Math.min(100,Math.round(powerIndex*.7+(b.potential||0)+10)),luck:Math.min(100,Math.round(40+Math.random()*40)),charisma:Math.min(100,Math.round((attributes.willpower+attributes.intelligence)/2+Math.random()*15))}}
